[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_ENABLEGITINFO = "true"
  PYTHON_VERSION="3.9.7"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.54.0"

[context.branch-deploy]
  # command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.54.0"
  command = "echo 'default context'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
