
  [build]
   distDir = "out""
  command = "echo 'default context'"
  publish = "out"

[build.environment]
  HUGO_VERSION = "0.142.0"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION ="22"
  PYTHON_VERSION ="3.13.1"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]


[context.branch-deploy]
  command = "echo 'default context'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
