[build]
    command = "hugo"
    publish = "."
    functions = "functions"

[build.environment]
    HUGO_VERSION = "0.142.0"
    PYTHON_VERSION ="3.13.1"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "hugo -b $DEPLOY_PRIME_URL"

[[headers]]
    for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
