[build]
  command = "echo 'default context'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  # command = "hugo  --minify --buildFuture -b $DEPLOY_PRIME_URL"
  command = "echo 'default context'"
  HUGO_VERSION = "0.54.0"

[context.branch-deploy]
  # command = "hugo  --minify -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.54.0"
  command = "echo 'default context'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
