
  [build]
  command = "echo 'default context'"
  publish = "out"

[build.environment]
  HUGO_VERSION = "0.142.0"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION ="22"
  PYTHON_VERSION ="3.13.1"


[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
